name: Deploy to GitHub Pages

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  deploy:
    uses: importantimport/.github/.github/workflows/pnpm-gh-pages.yml@main
    permissions:
      contents: write
    with:
      publish_dir: build
    strategy:
      matrix:
        node-version: [16, 18] # Adjust based on what worked before
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Rebuild sharp
        run: npm rebuild sharp

      - name: Install System Dependencies (for sharp)
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

